export enum ErrorCode {
  // Application errors
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  APPLICATION_FAILED_TO_CREATE = "APPLICATION_FAILED_TO_CREATE",
  AWS_COGNITO_ERROR = "AWS_COGNITO_ERROR",
  INVALID_AUTH_POVIDER = "INVALID_AUTH_POVIDER",
  INVALID_BREVO_API_KEY = "INVALID_BREVO_API_KEY",

  // Events
  EVENT_HANDLER_FAILED = "EVENT_HANDLER_FAILED",

  // AWS errors
  AWS_CONFIGURATIONS_ARE_MISSING = "AWS_CONFIGURATIONS_ARE_MISSING",
  AWS_COGNITO_SIGNUP_FAILED = "AWS_COGNITO_SIGNUP_FAILED",

  // Auth errors
  INVALID_AUTH_POVIDER_DATA = "INVALID_AUTH_POVIDER_DATA",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_AND_PASSWORD_REQUIRED = "EMAIL_AND_PASSWORD_REQUIRED",
  INVALID_SIGNUP_RESPONSE = "INVALID_SIGNUP_RESPONSE",
  INVALID_AUTH_DATA = "INVALID_AUTH_DATA",

  // User errors
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ACCOUNT_DISABLED = "USER_ACCOUNT_DISABLED",
  USER_ACCOUNT_FAILED = "USER_ACCOUNT_FAILED",
  USER_ACCOUNT_PENDING = "USER_ACCOUNT_PENDING",
  USER_MUST_BE_ACTIVE = "USER_MUST_BE_ACTIVE",
  USER_ACCOUNT_STATUS_IS_INVALID = "USER_ACCOUNT_STATUS_IS_INVALID",
  ONLY_PENDING_USERS_CAN_BE_ACTIVATED = "ONLY_PENDING_USERS_CAN_BE_ACTIVATED",
  FAILED_TO_CREATE_USER_ACCOUNT = "FAILED_TO_CREATE_USER_ACCOUNT",

  // Organization errors
  ORGANIZATION_ALREADY_EXIST = "ORGANIZATION_ALREADY_EXIST",
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  INVALID_ORGANIZATION_NAME = "INVALID_ORGANIZATION_NAME",
  INVALID_ORGANIZATION_SLUG = "INVALID_ORGANIZATION_SLUG",
  ORGANIZATION_SLUG_ALREADY_EXISTS = "ORGANIZATION_SLUG_ALREADY_EXISTS",
  SLUG_GENERATION_FAILED = "SLUG_GENERATION_FAILED",
  INCONSISTENT_ORGANIZATION_DATA = "INCONSISTENT_ORGANIZATION_DATA",

  // User Organization errors
  USER_ORGANIZATION_ALREADY_EXISTS = "USER_ORGANIZATION_ALREADY_EXISTS",
  USER_HAS_NO_ORGANIZATION = "USER_HAS_NO_ORGANIZATION",

  // Notification
  INVALID_EMAIL_NOTIFICATION_DATA = "INVALID_EMAIL_NOTIFICATION_DATA",
  INVALID_SMS_NOTIFICATION_DATA = "INVALID_SMS_NOTIFICATION_DATA",
  INVALID_PUSH_NOTIFICATION_DATA = "INVALID_PUSH_NOTIFICATION_DATA",
  INVALID_NOTIFICATION_PROVIDER = "INVALID_NOTIFICATION_PROVIDER",

  // Subject errors
  INVALID_SUBJECT_NAME = "INVALID_SUBJECT_NAME",
  INVALID_SUBJECT_COLOR = "INVALID_SUBJECT_COLOR",
  INVALID_SUBJECT_ORGANIZATION = "INVALID_SUBJECT_ORGANIZATION",
  INVALID_SUBJECT_USER = "INVALID_SUBJECT_USER",
  SUBJECT_ALREADY_EXISTS = "SUBJECT_ALREADY_EXISTS",
  SUBJECT_NOT_FOUND = "SUBJECT_NOT_FOUND",
}
