export enum ErrorCode {
  // Auth errors
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_AND_PASSWORD_REQUIRED = "EMAIL_AND_PASSWORD_REQUIRED",
  INVALID_SIGNUP_RESPONSE = "INVALID_SIGNUP_RESPONSE",
  INVALID_AUTH_DATA = "INVALID_AUTH_DATA",

  // User errors
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ACCOUNT_DISABLED = "USER_ACCOUNT_DISABLED",
  USER_ACCOUNT_FAILED = "USER_ACCOUNT_FAILED",
  USER_ACCOUNT_PENDING = "USER_ACCOUNT_PENDING",
  USER_MUST_BE_ACTIVE = "USER_MUST_BE_ACTIVE",
  ONLY_PENDING_USERS_CAN_BE_ACTIVATED = "ONLY_PENDING_USERS_CAN_BE_ACTIVATED",

  // Application errors
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  APPLICATION_FAILED_TO_CREATE_USER = "APPLICATION_FAILED_TO_CREATE_USER",
  AWS_COGNITO_ERROR = "AWS_COGNITO_ERROR",
}
