export enum ErrorCode {
  // Application errors
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  APPLICATION_FAILED_TO_CREATE_USER = "APPLICATION_FAILED_TO_CREATE_USER",
  AWS_COGNITO_ERROR = "AWS_COGNITO_ERROR",

  // Events
  EVENT_HANDLER_FAILED = "EVENT_HANDLER_FAILED",

  // AWS errors
  AWS_CONFIGURATIONS_ARE_MISSING = "AWS_CONFIGURATIONS_ARE_MISSING",
  AWS_COGNITO_SIGNUP_FAILED = "AWS_COGNITO_SIGNUP_FAILED",
  // Auth errors
  INVALID_AUTH_POVIDER_DATA = "INVALID_AUTH_POVIDER_DATA",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_AND_PASSWORD_REQUIRED = "EMAIL_AND_PASSWORD_REQUIRED",
  INVALID_SIGNUP_RESPONSE = "INVALID_SIGNUP_RESPONSE",
  INVALID_AUTH_DATA = "INVALID_AUTH_DATA",

  // User errors
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ACCOUNT_DISABLED = "USER_ACCOUNT_DISABLED",
  USER_ACCOUNT_FAILED = "USER_ACCOUNT_FAILED",
  USER_ACCOUNT_PENDING = "USER_ACCOUNT_PENDING",
  USER_MUST_BE_ACTIVE = "USER_MUST_BE_ACTIVE",
  USER_ACCOUNT_STATUS_IS_INVALID = "USER_ACCOUNT_STATUS_IS_INVALID",
  ONLY_PENDING_USERS_CAN_BE_ACTIVATED = "ONLY_PENDING_USERS_CAN_BE_ACTIVATED",
  FAILED_TO_CREATE_USER_ACCOUNT = "FAILED_TO_CREATE_USER_ACCOUNT",

  // Organization errors
  ORGANIZATION_ALREADY_EXIST = "ORGANIZATION_ALREADY_EXIST",
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  INVALID_ORGANIZATION_NAME = "INVALID_ORGANIZATION_NAME",
  INVALID_ORGANIZATION_SLUG = "INVALID_ORGANIZATION_SLUG",
  ORGANIZATION_SLUG_ALREADY_EXISTS = "ORGANIZATION_SLUG_ALREADY_EXISTS",
  SLUG_GENERATION_FAILED = "SLUG_GENERATION_FAILED",
  INCONSISTENT_ORGANIZATION_DATA = "INCONSISTENT_ORGANIZATION_DATA",
}
