FROM node:20-alpine AS builder

WORKDIR /app

ARG PORT
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_S3_BUCKET
ARG AWS_COGNITO_USER_POOL_ID
ARG AWS_COGNITO_USER_POOL_CLIENT_ID
ARG AWS_COGNITO_USER_POOL_CLIENT_SECRET
ARG NODE_ENVIRONMENT
ARG AUTH_JWT_SECRET
ARG AUTH_JWT_EXPIRES_IN
ARG AUTH_JWT_REFRESH_SECRET
ARG AUTH_JWT_REFRESH_EXPIRES_IN
ARG BREVO_API_KEY
ARG FRONTEND_DOMAIN_URL
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISHABLE_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CALLBACK_URL


ENV PORT=${PORT}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
ENV AWS_COGNITO_USER_POOL_CLIENT_ID=${AWS_COGNITO_USER_POOL_CLIENT_ID}
ENV AWS_COGNITO_USER_POOL_CLIENT_SECRET=${AWS_COGNITO_USER_POOL_CLIENT_SECRET}
ENV NODE_ENVIRONMENT=${NODE_ENVIRONMENT}
ENV AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
ENV AUTH_JWT_EXPIRES_IN=${AUTH_JWT_EXPIRES_IN}
ENV AUTH_JWT_REFRESH_SECRET=${AUTH_JWT_REFRESH_SECRET}
ENV AUTH_JWT_REFRESH_EXPIRES_IN=${AUTH_JWT_REFRESH_EXPIRES_IN}
ENV BREVO_API_KEY=${BREVO_API_KEY}
ENV FRONTEND_DOMAIN_URL=${FRONTEND_DOMAIN_URL}
ENV STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
ENV STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
ENV STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}


COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV PORT=${PORT}
ENV DATABASE_HOST=${DATABASE_HOST}

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

EXPOSE ${PORT}

CMD ["node", "dist/main"]